# Nodes :
AnimationEngine: {
    AnimatorProcessor: Animator Processor {
       link: AnimatorProcessor
    }
    AnimationData: Animation Data {
       link: AnimationData
    }
}
MagicEngine: {
    EntityEngine: {
        EntityAnimator: Entity Animator {
           link: EntityAnimator
        }
    }
}

# Links :
AnimationEngine.AnimatorProcessor -> AnimationEngine.AnimationManager: Process Queue every tick {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
AnimationEngine.AnimationManager -> AnimationEngine.AnimationData: Process {
source-arrowhead: {}
target-arrowhead: Queue of{shape: arrow}
}
AnimationEngine.AnimationManager -> MagicEngine.EntityEngine.EntityAnimator: Animate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
