# Nodes :
BoardEngine: {
    Coordinate: Coordinate {
       link: Coordinate
    }
    WorldEngine: {
        WorldManager: World Manager {
           link: WorldManager
        }
    }
}
MagicEngine: {
    MagicManager: Magic Manager {
       link: MagicManager
    }
}

# Links :
BoardEngine.BoardManager -- BoardEngine.Coordinate: {style.stroke-dash: 3}
BoardEngine.WorldEngine.WorldManager -> BoardEngine.BoardManager: Get active World {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.BoardManager -> MagicEngine.MagicManager: Manipulate Cell {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
