# Nodes :
BoardEngine: {
    World: World {
       link: World
    }
    WorldManager: World Manager {
       link: WorldManager
    }
}
GameplayManager: {
    GameManager: Game Manager {
       link: GameManager
    }
}

# Links :
BoardEngine.ChunkManager -> BoardEngine.World: Load Chunks {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.ChunkManager -> BoardEngine.World: Unload Chunks {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldManager -> BoardEngine.ChunkManager: Update view coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
GameplayManager.GameManager -> BoardEngine.ChunkManager: Update Player coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
