# Nodes :
BoardEngine: {
    WorldEngine: {
        World: World {
           link: World
        }
    }
}

# Links :
BoardEngine.WorldEngine.CoolNoiseGenerator -- BoardEngine.WorldEngine.World: {style.stroke-dash: 3}
