# Nodes :
UI: {
    DeckManager: Deck Manager {
       link: DeckManager
    }
}
BoardEngine: {
    AreaMaker: Area Maker {
       link: AreaMaker
    }
    BoardManager: Board Manager {
       link: BoardManager
    }
}
MagicEngine: {
    EntityEngine: {
        AI: {
            IntentAI: IntentAI {
               link: IntentAI
            }
            PlayerAI: PlayerAI {
               link: PlayerAI
            }
        }
        EntityManager: Entity Manager {
           link: EntityManager
        }
        Entity: Entity {
           link: Entity
        }
        EntityAnimator: Entity Animator {
           link: EntityAnimator
        }
    }
    MagicManager: Magic Manager {
       link: MagicManager
    }
    Spells: {
        Grimoire: Grimoire {
           link: Grimoire
        }
    }
}

# Links :
BoardEngine.Coordinate -- UI.DeckManager: {style.stroke-dash: 3}
BoardEngine.Coordinate -- MagicEngine.EntityEngine.AI.PlayerAI: {style.stroke-dash: 3}
BoardEngine.Coordinate -- MagicEngine.EntityEngine.EntityManager: {style.stroke-dash: 3}
BoardEngine.Coordinate -- MagicEngine.EntityEngine.EntityAnimator: {style.stroke-dash: 3}
BoardEngine.Coordinate -- MagicEngine.MagicManager: {style.stroke-dash: 3}
BoardEngine.Coordinate -- MagicEngine.Spells.Grimoire: {style.stroke-dash: 3}
BoardEngine.BoardManager -- BoardEngine.Coordinate: {style.stroke-dash: 3}
BoardEngine.AreaMaker -> BoardEngine.Coordinate: ...make a list of Coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.Coordinate -> MagicEngine.EntityEngine.AI.IntentAI: Can have fix target {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity -> BoardEngine.Coordinate: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
