# Nodes :
EntityEngine: {
    EntityComposition: {
        в_Positional: {
            Positional: Positional {
               link: Positional
            }
        }
    }
}
BoardEngine: {
    AreaMaker: Area Maker {
       link: AreaMaker
    }
}
WorldEngine: {
    CanvasEngine: {
        DimensionCanvasTilemap: Dimension Canvas Tilemap {
           link: DimensionCanvasTilemap
        }
        DimensionCanvas: Dimension Canvas {
           link: DimensionCanvas
        }
    }
}
WorldGeneratorEngine: {
    Tools: {
        QuickPainter: Quick Painter {
           link: QuickPainter
        }
    }
}

# Links :
BoardEngine.Coordinate -- EntityEngine.EntityComposition.в_Positional.Positional: {style.stroke-dash: 3}
BoardEngine.Coordinate -- WorldEngine.CanvasEngine.DimensionCanvasTilemap: {style.stroke-dash: 3}
BoardEngine.Coordinate -- WorldEngine.CanvasEngine.DimensionCanvas: {style.stroke-dash: 3}
BoardEngine.Coordinate -- WorldGeneratorEngine.Tools.QuickPainter: {style.stroke-dash: 3}
BoardEngine.AreaMaker -> BoardEngine.Coordinate: ...make a list of Coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
