# Nodes :
WorldEngine: {
    WorldGenerationEngine: {
        WorldGenerator: World Generator {
           link: WorldGenerator
        }
    }
}

# Links :
WorldEngine.DimensionEngine.DimensionEntrance -- WorldEngine.WorldGenerationEngine.WorldGenerator: {style.stroke-dash: 3}
