# Nodes :
BoardEngine: {
    Coordinate: Coordinate {
       link: Coordinate
    }
}
GameplayManager: {
    GameManager: Game Manager {
       link: GameManager
    }
}
MagicEngine: {
    EntityEngine: {
        EntityManager: Entity Manager {
           link: EntityManager
        }
        EntityAnimator: Entity Animator {
           link: EntityAnimator
        }
        State: State {
           link: State
        }
        AI: {
            IntentAI: IntentAI {
               link: IntentAI
            }
            EntityAI: EntityAI {
               link: EntityAI
            }
        }
    }
}

# Links :
MagicEngine.EntityEngine.Entity -> GameplayManager.GameManager: Listen for OnTelefrag {
source-arrowhead: Player{}
target-arrowhead: {shape: arrow}
}
GameplayManager.GameManager -> MagicEngine.EntityEngine.Entity: Play Turn {
source-arrowhead: {}
target-arrowhead: All Entity{shape: arrow}
}
MagicEngine.EntityEngine.EntityManager -> MagicEngine.EntityEngine.Entity: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.EntityAnimator -> MagicEngine.EntityEngine.Entity: Linked to {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity <-> MagicEngine.EntityEngine.AI.EntityAI: Play turn {
source-arrowhead: {shape: arrow}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity -> MagicEngine.EntityEngine.State: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity -> BoardEngine.Coordinate: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity -> MagicEngine.EntityEngine.AI.IntentAI: Can have pinned target {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
