# Nodes :
EntityEngine: {
    EntityManagement: {
        EntityRegistry: Entity Registry {
           link: EntityRegistry
        }
    }
}

# Links :
EntityEngine.EntityComposition.с_Entity.Entity -- EntityEngine.EntityManagement.EntityRegistry: {style.stroke-dash: 3}
