# Nodes :
GameEngine: {
    CharacterControllerManager: Character Controller Manager {
       link: CharacterControllerManager
    }
}
Test: {
    PrettHierarchy: Prett Hierarchy {
       link: PrettHierarchy
    }
}
EntityEngine: {
    EntityComposition: {
        н_Experiencable: {
            XpGainEvent: Xp Gain Event {
               link: XpGainEvent
            }
        }
        в_Positional: {
            Positional: Positional {
               link: Positional
            }
            PositionalView: Positional View {
               link: PositionalView
            }
        }
        с_Entity: {
            Entity: Entity {
               link: Entity
            }
        }
        к_Alive: {
            HpChangeEvent: Hp Change Event {
               link: HpChangeEvent
            }
        }
        л_Afflictable: {
            State: State {
               link: State
            }
        }
    }
    EntityManagement: {
        EntityFactory: Entity Factory {
           link: EntityFactory
        }
        EntityRegistry: Entity Registry {
           link: EntityRegistry
        }
    }
}
BoardEngine: {
    BoardManager: Board Manager {
       link: BoardManager
    }
    AreaMaker: Area Maker {
       link: AreaMaker
    }
    Area: Area {
       link: Area
    }
    Coordinate: Coordinate {
       link: Coordinate
    }
    TilemapEngine: {
        TilemapManager: Tilemap Manager {
           link: TilemapManager
        }
    }
    MovementAttempt: Movement Attempt {
       link: MovementAttempt
    }
}
WorldEngine: {
    DimensionEngine: {
        DimensionEntrance: Dimension Entrance {
           link: DimensionEntrance
        }
        Dimension: Dimension {
           link: Dimension
        }
        DimensionManager: Dimension Manager {
           link: DimensionManager
        }
    }
    CanvasEngine: {
        DimensionCanvasReference: Dimension Canvas Reference {
           link: DimensionCanvasReference
        }
        DimensionCanvasTilemap: Dimension Canvas Tilemap {
           link: DimensionCanvasTilemap
        }
        DimensionCanvas: Dimension Canvas {
           link: DimensionCanvas
        }
        Cell: Cell {
           link: Cell
        }
    }
    WorldManager: World Manager {
       link: WorldManager
    }
    WorldGenerationEngine: {
        WorldGenerator: World Generator {
           link: WorldGenerator
        }
        DimensionGenerator: Dimension Generator {
           link: DimensionGenerator
        }
    }
}
WorldGeneratorEngine: {
    Tools: {
        QuickPainter: Quick Painter {
           link: QuickPainter
        }
        ToClean: {
            RuleTile: {
                RuleTile: Rule Tile {
                   link: RuleTile
                }
            }
            WaveFunctionCollapse: {
                LocalPattern: {
                    AbstractLocalPattern: Abstract Local Pattern {
                       link: AbstractLocalPattern
                    }
                }
            }
            ColorsAndImages: {
                ImagePalette: Image Palette {
                   link: ImagePalette
                }
                Image: Image {
                   link: Image
                }
            }
        }
    }
}
InteractionEngine: {
    InteractionManager: Interaction Manager {
       link: InteractionManager
    }
    InteractionQueue: Interaction Queue {
       link: InteractionQueue
    }
}
SpellEngine: {
    SpellCondition: Spell Condition {
       link: SpellCondition
    }
    Spell: Spell {
       link: Spell
    }
    SpellEffect: Spell Effect {
       link: SpellEffect
    }
}
MagicEngine: {
    MagicManager: Magic Manager {
       link: MagicManager
    }
    GrimoireEngine: {
        GrimoirePage: Grimoire Page {
           link: GrimoirePage
        }
        Grimoire: Grimoire {
           link: Grimoire
        }
    }
}
Misc: {
    ChangeUpdater: Change Updater {
       link: ChangeUpdater
    }
}
Builder: {
    Editors: {
        ImagePaletteEditor: Image Palette Editor {
           link: ImagePaletteEditor
        }
        GeneratorMonitorEditor: Generator Monitor Editor {
           link: GeneratorMonitorEditor
        }
    }
    Helper: {
        SaveTextField: Save Text Field {
           link: SaveTextField
        }
        SerializedPropertyHelper: Serialized Property Helper {
           link: SerializedPropertyHelper
        }
    }
}
SocialEngine: {
    CharacterEngine: {
        CharacterRegistry: Character Registry {
           link: CharacterRegistry
        }
    }
}

# Links :
MagicEngine.MagicManager -- SpellEngine.Spell: {style.stroke-dash: 3}
MagicEngine.MagicManager -- SpellEngine.SpellEffect: {style.stroke-dash: 3}
MagicEngine.MagicManager -- SpellEngine.SpellCondition: {style.stroke-dash: 3}
EntityEngine.EntityComposition.с_Entity.Entity -- EntityEngine.EntityManagement.EntityRegistry: {style.stroke-dash: 3}
MagicEngine.GrimoireEngine.Grimoire -- MagicEngine.GrimoireEngine.GrimoirePage: {style.stroke-dash: 3}
MagicEngine.GrimoireEngine.Grimoire -- SpellEngine.Spell: {style.stroke-dash: 3}
BoardEngine.Coordinate -- EntityEngine.EntityComposition.в_Positional.Positional: {style.stroke-dash: 3}
BoardEngine.Coordinate -- WorldEngine.CanvasEngine.DimensionCanvasTilemap: {style.stroke-dash: 3}
BoardEngine.Coordinate -- WorldEngine.CanvasEngine.DimensionCanvas: {style.stroke-dash: 3}
BoardEngine.Coordinate -- WorldGeneratorEngine.Tools.QuickPainter: {style.stroke-dash: 3}
WorldEngine.DimensionEngine.Dimension -- WorldEngine.CanvasEngine.DimensionCanvas: {style.stroke-dash: 3}
WorldEngine.DimensionEngine.Dimension -- WorldEngine.DimensionEngine.DimensionManager: {style.stroke-dash: 3}
WorldEngine.DimensionEngine.Dimension -- WorldEngine.WorldGenerationEngine.WorldGenerator: {style.stroke-dash: 3}
WorldEngine.CanvasEngine.DimensionCanvas -- WorldGeneratorEngine.Tools.QuickPainter: {style.stroke-dash: 3}
WorldEngine.CanvasEngine.Cell -- WorldEngine.CanvasEngine.DimensionCanvasTilemap: {style.stroke-dash: 3}
WorldEngine.CanvasEngine.Cell -- WorldEngine.CanvasEngine.DimensionCanvas: {style.stroke-dash: 3}
WorldEngine.DimensionEngine.DimensionEntrance -- WorldEngine.WorldGenerationEngine.WorldGenerator: {style.stroke-dash: 3}
WorldGeneratorEngine.Tools.ToClean.ColorsAndImages.ImagePalette -- Builder.Editors.ImagePaletteEditor: {style.stroke-dash: 3}
EntityEngine.EntityManagement.EntityRegistry -> EntityEngine.EntityComposition.в_Positional.Positional: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
WorldEngine.DimensionEngine.DimensionManager -> BoardEngine.BoardManager: Get active Dimension {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.AreaMaker -> BoardEngine.Coordinate: ...make a list of Coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.Area -> BoardEngine.AreaMaker: Convert an Area to... {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.AreaMaker -> MagicEngine.MagicManager: Get Spells' AoE {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.AreaMaker -> SelectionManager: Get Spells' range cast {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.BoardManager -> MagicEngine.MagicManager: Manipulate Cell {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
