# Nodes :
SpellEngine: {
    Spell: Spell {
       link: Spell
    }
}
MagicEngine: {
    GrimoireEngine: {
        GrimoirePage: Grimoire Page {
           link: GrimoirePage
        }
    }
}

# Links :
MagicEngine.GrimoireEngine.Grimoire -- MagicEngine.GrimoireEngine.GrimoirePage: {style.stroke-dash: 3}
MagicEngine.GrimoireEngine.Grimoire -- SpellEngine.Spell: {style.stroke-dash: 3}
