# Nodes :
MagicEngine: {
    GrimoireEngine: {
        Grimoire: Grimoire {
           link: Grimoire
        }
    }
}

# Links :
MagicEngine.GrimoireEngine.Grimoire -- MagicEngine.GrimoireEngine.GrimoirePage: {style.stroke-dash: 3}
