# Nodes :
WorldGeneratorEngine: {
    Tools: {
        ToClean: {
            ColorsAndImages: {
                ImagePalette: Image Palette {
                   link: ImagePalette
                }
            }
        }
    }
}

# Links :
WorldGeneratorEngine.Tools.ToClean.ColorsAndImages.ImagePalette -- Builder.Editors.ImagePaletteEditor: {style.stroke-dash: 3}
