# Nodes :
BoardEngine: {
    DimensionCoordinate: Dimension Coordinate {
       link: DimensionCoordinate
    }
    BoardManager: Board Manager {
       link: BoardManager
    }
    AreaMaker: Area Maker {
       link: AreaMaker
    }
}
SpellEngine: {
    SpellCondition: Spell Condition {
       link: SpellCondition
    }
    Spell: Spell {
       link: Spell
    }
    SpellEffect: Spell Effect {
       link: SpellEffect
    }
}

# Links :
MagicEngine.MagicManager -- SpellEngine.Spell: {style.stroke-dash: 3}
MagicEngine.MagicManager -- SpellEngine.SpellEffect: {style.stroke-dash: 3}
MagicEngine.MagicManager -- SpellEngine.SpellCondition: {style.stroke-dash: 3}
BoardEngine.DimensionCoordinate -- MagicEngine.MagicManager: {style.stroke-dash: 3}
BoardEngine.AreaMaker -> MagicEngine.MagicManager: Get Spells' AoE {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.BoardManager -> MagicEngine.MagicManager: Manipulate Cell {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
