# Nodes :
MagicEngine: {
    EntityEngine: {
        EntityManager: Entity Manager {
           link: EntityManager
        }
    }
}

# Links :
MagicEngine.EntityEngine.EntityManager -- MagicEngine.EntityEngine.Movement: {style.stroke-dash: 3}
