# Nodes :
WorldGeneratorEngine: {
    Tools: {
        ToClean: {
            RuleTile: {
                RuleTile: Rule Tile {
                   link: RuleTile
                }
            }
        }
    }
}

# Links :
