# Nodes :
MagicEngine: {
    MagicManager: Magic Manager {
       link: MagicManager
    }
    GrimoireEngine: {
        Grimoire: Grimoire {
           link: Grimoire
        }
    }
}

# Links :
MagicEngine.MagicManager -- SpellEngine.Spell: {style.stroke-dash: 3}
MagicEngine.GrimoireEngine.Grimoire -- SpellEngine.Spell: {style.stroke-dash: 3}
