# Nodes :
MagicEngine: {
    EntityEngine: {
        Entity: Entity {
           link: Entity
        }
    }
}

# Links :
MagicEngine.EntityEngine.Entity -> MagicEngine.EntityEngine.State: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
