# Nodes :
BoardEngine: {
    WorldManager: World Manager {
       link: WorldManager
    }
    SelectionManager: Selection Manager {
       link: SelectionManager
    }
}

# Links :
BoardEngine.WorldManager -> BoardEngine.TilemapManager: Uses {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.SelectionManager -> BoardEngine.TilemapManager: Uses {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
