# Nodes :
BoardEngine: {
    ChunkManager: Chunk Manager {
       link: ChunkManager
    }
    TilemapManager: Tilemap Manager {
       link: TilemapManager
    }
    BoardManager: Board Manager {
       link: BoardManager
    }
    WorldEngine: {
        World: World {
           link: World
        }
    }
}

# Links :
BoardEngine.WorldEngine.WorldManager -> BoardEngine.BoardManager: Get active World {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldEngine.WorldManager -> BoardEngine.ChunkManager: Update view coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldEngine.WorldManager -> BoardEngine.WorldEngine.World: Instantiate {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldEngine.WorldManager -> BoardEngine.TilemapManager: Uses {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
