# Nodes :
WorldEngine: {
    DimensionEngine: {
        DimensionEntrance: Dimension Entrance {
           link: DimensionEntrance
        }
        Dimension: Dimension {
           link: Dimension
        }
    }
}

# Links :
WorldEngine.DimensionEngine.Dimension -- WorldEngine.WorldGenerationEngine.WorldGenerator: {style.stroke-dash: 3}
WorldEngine.DimensionEngine.DimensionEntrance -- WorldEngine.WorldGenerationEngine.WorldGenerator: {style.stroke-dash: 3}
