# Nodes :
BoardEngine: {
    FogVision: Fog Vision {
       link: FogVision
    }
}

# Links :
BoardEngine.FogVision -> BoardEngine.FogManager: Update the Fog Vision {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
