# Nodes :
Misc: {
    SceneReferencer: Scene Referencer {
       link: SceneReferencer
    }
}
BoardEngine: {
    ChunkManager: Chunk Manager {
       link: ChunkManager
    }
    World: World {
       link: World
    }
    FogVision: Fog Vision {
       link: FogVision
    }
    WorldManager: World Manager {
       link: WorldManager
    }
    AreaMaker: Area Maker {
       link: AreaMaker
    }
    Area: Area {
       link: Area
    }
    TilemapManager: Tilemap Manager {
       link: TilemapManager
    }
    SelectionManager: Selection Manager {
       link: SelectionManager
    }
    Coordinate: Coordinate {
       link: Coordinate
    }
    WorldGenerationParameter: World Generation Parameter {
       link: WorldGenerationParameter
    }
    WorldGenerator: World Generator {
       link: WorldGenerator
    }
    FogManager: Fog Manager {
       link: FogManager
    }
    BoardManager: Board Manager {
       link: BoardManager
    }
}
UI: {
    InputManager: Input Manager {
       link: InputManager
    }
    DeckManager: Deck Manager {
       link: DeckManager
    }
    MouseInput: Mouse Input {
       link: MouseInput
    }
    HandSpell: Hand Spell {
       link: HandSpell
    }
}
MagicEngine: {
    EntityEngine: {
        EntityAnimator: Entity Animator {
           link: EntityAnimator
        }
        Affliction: Affliction {
           link: Affliction
        }
        EntityManager: Entity Manager {
           link: EntityManager
        }
        AI: {
            IntentAI: IntentAI {
               link: IntentAI
            }
            PlayerAI: PlayerAI {
               link: PlayerAI
            }
            EntityAI: EntityAI {
               link: EntityAI
            }
            BasicEnemyAI: Basic EnemyAI {
               link: BasicEnemyAI
            }
        }
        State: State {
           link: State
        }
        Entity: Entity {
           link: Entity
        }
        EntityAnimatorEvent: Entity Animator Event {
           link: EntityAnimatorEvent
        }
        Movement: Movement {
           link: Movement
        }
    }
    Spells: {
        SpellEffect: Spell Effect {
           link: SpellEffect
        }
        SpellCondition: Spell Condition {
           link: SpellCondition
        }
        Grimoire: Grimoire {
           link: Grimoire
        }
        Spell: Spell {
           link: Spell
        }
    }
    MagicManager: Magic Manager {
       link: MagicManager
    }
}
GameplayManager: {
    InitiativeManager: Initiative Manager {
       link: InitiativeManager
    }
    GameModeManager: Game Mode Manager {
       link: GameModeManager
    }
    GameManager: Game Manager {
       link: GameManager
    }
    PassTurnClock: Pass Turn Clock {
       link: PassTurnClock
    }
}
AnimationEngine: {
    AnimationManager: Animation Manager {
       link: AnimationManager
    }
    AnimatorProcessor: Animator Processor {
       link: AnimatorProcessor
    }
    AnimationTrigger: Animation Trigger {
       link: AnimationTrigger
    }
    AnimationData: Animation Data {
       link: AnimationData
    }
}

# Links :
BoardEngine.Coordinate -- UI.DeckManager: {style.stroke-dash: 3}
BoardEngine.Coordinate -- MagicEngine.EntityEngine.EntityAnimator: {style.stroke-dash: 3}
BoardEngine.Coordinate -- MagicEngine.MagicManager: {style.stroke-dash: 3}
MagicEngine.Spells.Grimoire -- MagicEngine.Spells.Spell: {style.stroke-dash: 3}
MagicEngine.MagicManager -- MagicEngine.Spells.Spell: {style.stroke-dash: 3}
MagicEngine.MagicManager -- MagicEngine.Spells.SpellEffect: {style.stroke-dash: 3}
MagicEngine.MagicManager -- MagicEngine.Spells.SpellCondition: {style.stroke-dash: 3}
BoardEngine.BoardManager -- BoardEngine.Coordinate: {style.stroke-dash: 3}
BoardEngine.ChunkManager -> BoardEngine.World: Load Chunks {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.ChunkManager -> BoardEngine.World: Unload Chunks {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldGenerator -> BoardEngine.World: Generated by {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.FogVision -> BoardEngine.FogManager: Update the Fog Vision {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldManager -> BoardEngine.ChunkManager: Update view coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldManager -> BoardEngine.World: Instantiate {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldManager -> BoardEngine.TilemapManager: Uses {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.AreaMaker -> BoardEngine.Coordinate: ...make a list of Coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.Area -> BoardEngine.AreaMaker: Convert an Area to... {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.AreaMaker -> MagicEngine.MagicManager: Get Spells' AoE {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.AreaMaker -> BoardEngine.SelectionManager: Get Spells' range cast {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.SelectionManager -> BoardEngine.TilemapManager: Uses {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.WorldManager -> BoardEngine.BoardManager: Get active World {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.EntityAnimator -> MagicEngine.EntityEngine.Entity: Linked to {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.EntityManager -> MagicEngine.EntityEngine.Entity: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.AI.IntentAI -> BoardEngine.SelectionManager: Shows Intent {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.AI.EntityAI -> MagicEngine.EntityEngine.AI.IntentAI: Inherits {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.Spells.Spell -> MagicEngine.EntityEngine.AI.IntentAI: Can have intent {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity -> MagicEngine.EntityEngine.AI.IntentAI: Can have pinned target {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.Coordinate -> MagicEngine.EntityEngine.AI.IntentAI: Can have fix target {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.AI.IntentAI -> MagicEngine.EntityEngine.AI.BasicEnemyAI: Inherits {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.Spells.Grimoire -> MagicEngine.EntityEngine.AI.BasicEnemyAI: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
GameplayManager.GameManager -> MagicEngine.EntityEngine.AI.BasicEnemyAI: Get Player {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity <-> MagicEngine.EntityEngine.AI.EntityAI: Play turn {
source-arrowhead: {shape: arrow}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity -> MagicEngine.EntityEngine.State: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity -> BoardEngine.Coordinate: Has {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
BoardEngine.BoardManager -> MagicEngine.MagicManager: Manipulate Cell {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
GameplayManager.GameManager -> MagicEngine.MagicManager: Cast Player's spells {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
GameplayManager.GameManager -> MagicEngine.MagicManager: Cast Telefrag {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.EntityEngine.Entity -> GameplayManager.GameManager: Listen for OnTelefrag {
source-arrowhead: Player{}
target-arrowhead: {shape: arrow}
}
GameplayManager.GameManager -> BoardEngine.ChunkManager: Update Player coordinate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
GameplayManager.InitiativeManager -> GameplayManager.GameManager: Get Initiative list {style.stroke-dash: 3
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
GameplayManager.GameManager -> MagicEngine.EntityEngine.Entity: Play Turn {
source-arrowhead: {}
target-arrowhead: All Entity{shape: arrow}
}
AnimationEngine.AnimationManager -> AnimationEngine.AnimationData: Process {
source-arrowhead: {}
target-arrowhead: Queue of{shape: arrow}
}
AnimationEngine.AnimationManager -> MagicEngine.EntityEngine.EntityAnimator: Animate {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
AnimationEngine.AnimatorProcessor -> AnimationEngine.AnimationManager: Process Queue every tick {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
MagicEngine.Spells.SpellEffect -> AnimationEngine.AnimationTrigger: Has {
source-arrowhead: {}
target-arrowhead: {shape: arrow}
}
